# Generated by Django 2.1.7 on 2019-03-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='타이틀')),
                ('content', models.TextField(verbose_name='내용')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='생성일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
        ),
    ]
